### ISSUE TITLE
'ord' in websocket requests

### ISSUE THREAD

**Issue by skyrover7** [ordpool-space/ordpool-parser#10]
It would be an awesome feature to add an additional request to the websocket that sends a message for each ord that is found.

i am currently doing this using the `transactions` request from the mempoo.space api and then parsing them using the ordpool package. but this seems redundant as I am having to hit the mempool API to parse each transaction

**Comment by skyrover7** [comment]
well right now i have managed to store the ords in the mempool by doing the following

* use mempool.space websocket to get tranasctions in the mempool (6 at a time)
* parse each transaction to check for ords using this library
* store the ord in a database so it can be checked against in an application workflow
* clear the database table when a new block is confirmed and restart the process

Since ordpool is a fork of mempool, id imagine the websocket functionality can be updated, and if so, it would be cool to request `ord` from the websocket, and get back only transactions that have inscriptions in them, or ideally the actual parsed inscription. Since the websocket is sending out transaction ids, you could pre-parse those and only return the inscriptions

**Comment by hans-crypto** [comment]
This is beyond the scope of the ordpool-parser. It is really only a parser for transactions. 🙂
