### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by skyrover7** [ordpool-space/ordpool-parser#9]
It was sooo helpful to have a testnet ordpool live. are you aware that it is not online/synced?

**Comment by hans-crypto** [comment]
I'm 200% aware of this:
https://twitter.com/OrdpoolSpace/status/1755508213632450724

Right now I'm happy that Ordpool is not completely down. And I'm working hard on finding a long-term sponsor for an own backend!

**Comment by skyrover7** [comment]
dm'ed on discord
